### PR TITLE
exception messages feedback for wasm

### LINKED ISSUE #11: Give exception back to wasm
As of now, our shim wrapper functions for wasm does not give exception back. We are mostly ignoring exceptions or just returning -1 as function result.

For example ```__get_state``` wrapper for wasm: https://github.com/kleash/wasmer-chaincode-test/blob/bfc746d12cd70b67034fd9a5e83d37d26d14b0af/wasmcc/main.go#L98

Here we just ignore the error and returns -1 if we are unable to retrieve from the state.

A mechanism is required to propagate this exception back to wasm so that wasm chaincode developers can use the exception message and stack trace for debugging.

### PR DESCRIPTION
**Pull request by kleash**
- Added more default exception messages
- All error messages being stored in global Resolver struct
- new fn __get_exception_msg for wasm chaincodes to read exception message
- logging improvement

Fixes #11

### CODE REVIEW

File: wasmcc/wasmcc.go [hunk 1]
```diff
@@ -22,8 +22,19 @@ import (
 	wasm_validation "github.com/perlin-network/life/wasm-validation"
 )
 
-const CHAINCODE_EXISTS = "{\"code\":101, \"reason\": \"chaincode exists with same name\"}"
-const UKNOWN_ERROR = "{\"code\":301, \"reason\": \"uknown error : %s\"}"
+//Exception messages for WASMCC
+const (
+	ChaincodeExists = "{\"code\":401, \"reason\": \"chaincode exists with same name\"}"
+	UnknownError    = "{\"code\":402, \"reason\": \"unknown error : %s\"}"
+	FnNotPresent    = "{\"code\":403, \"reason\": \"fn doesn't exists in installed wasm chaincode : %s\"}"
```
Comment (MHBauer) [inline wasmcc/wasmcc.go]: singular "exist".

File: wasmcc/wasmcc.go [hunk 2]
```diff
@@ -22,8 +22,19 @@ import (
...
+)
+
+//Exception messages for Host Functions
+const (
+	TxnParameterOutOfBound = "No transaction parameter present for give position"
+	NoResultForGetState    = "no state for give key"
```
Comment (MHBauer) [inline wasmcc/wasmcc.go]: "given" key

File: wasmcc/wasmcc.go [hunk 3]
```diff
@@ -22,8 +22,19 @@ import (
...
 )
 
-const CHAINCODE_EXISTS = "{\"code\":101, \"reason\": \"chaincode exists with same name\"}"
-const UKNOWN_ERROR = "{\"code\":301, \"reason\": \"uknown error : %s\"}"
+//Exception messages for WASMCC
+const (
+	ChaincodeExists = "{\"code\":401, \"reason\": \"chaincode exists with same name\"}"
+	UnknownError    = "{\"code\":402, \"reason\": \"unknown error : %s\"}"
+	FnNotPresent    = "{\"code\":403, \"reason\": \"fn doesn't exists in installed wasm chaincode : %s\"}"
+)
```
Comment (MHBauer) [inline wasmcc/wasmcc.go:30]: Why are these json formatted?

**Review by MHBauer — CHANGES_REQUESTED** [review]
Nits on spelling.

Is there a test for these?

I'll have to check what's exposed by the flogger, but I would expect some support for structuring the function names explicitly rather than including them in the log text.

Things like __delete_state might be better done using with. logger.with("function","__delete_state")

File: wasmcc/wasmcc.go (hunk 3 above)
Comment (kleash) [reply wasmcc/wasmcc.go:30]: these are being returned as wasmcc execution response. So if someone using sdk, would be easier for parsing.

Plus, reference from fabric-samples :smiley:

Comment (kleash) [reply wasmcc/wasmcc.go]: Thanks for pointing out. Fixed it

File: wasmcc/wasmcc.go (hunk 2 above)
Comment (kleash) [reply wasmcc/wasmcc.go]: Thanks for pointing out. Fixed it

File: wasmcc/wasmcc.go (hunk 1 above)
Comment (kleash) [reply wasmcc/wasmcc.go]: Fixed

**Comment by kleash** [comment]
> Nits on spelling.
> 
> Is there a test for these?
> 
> I'll have to check what's exposed by the flogger, but I would expect some support for structuring the function names explicitly rather than including them in the log text.
> 
> Things like __delete_state might be better done using with. logger.with("function","__delete_state")

I am still trying to figure out how to create test cases for it. This function is going to return error message to wasm chaincode directly.

I will look into logger.with. Never used it

File: wasmcc/wasmcc.go (hunk 3 above)
Comment (MHBauer) [reply wasmcc/wasmcc.go:30]: I see. This sets off a bit of alarm for me. Given the reason and the simplicity, we can allow it for now.

It'd probably be overengineering to insist on a struct and json marshalling. 

For interoperability reasons, having a defined struct in a separate package would be best for golang parsing of the messages, but would not help any other language.

**Review by MHBauer — COMMENTED** [review]
For the test as error returned to wasm chaincode, is this pushed directly back into the running wasm or back to the client?

**Comment by kleash** [comment]
> For the test as error returned to wasm chaincode, is this pushed directly back into the running wasm or back to the client?

back to running wasm

**Comment by MHBauer** [comment]
That make sense to me. So that's part of the API we're providing to wasm users, then it's good to document that interface.

For this it will mean that they have to have a json processor in their wasm code, which might be a bit more challenging than providing more basic error codes + a glossary to the programmer.

**Comment by kleash** [comment]
JSON is returned directly to the client as a transaction response.

Added information on exception message fn in README : https://github.com/hyperledger-labs/fabric-chaincode-wasm/pull/31/files#diff-04c6e90faac2675aa89e2176d2eec7d8

**Review by MHBauer — APPROVED** [review]
I think it's fine now.

Any comments @swetharepakula
